In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

In [2]:
from src.data_preprocessing import prepare_crime_data
from src.feature_engineering import engineer_features

In [3]:
data_path = project_root / "data" / "raw" / "crime_dataset_india.csv"

df = prepare_crime_data(data_path)
df = engineer_features(df)

print("Final dataset shape:", df.shape)
df.head()

Final dataset shape: (6458, 25)

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,...,Month,MonthName,Day,DayOfWeek,Hour,IsWeekend,IsNightCrime,VictimAgeGroup,IsCaseClosed,CaseResolutionDays
5,6,2020-01-02 03:00:00,2020-01-01 05:00:00,2020-01-01 17:09:00,Delhi,442,ASSAULT,16,M,Firearm,...,1,January,1,Wednesday,5,False,True,Child,True,88.0
10,11,2020-01-02 13:00:00,2020-01-01 10:00:00,2020-01-01 19:42:00,Delhi,260,FRAUD,71,M,Explosives,...,1,January,1,Wednesday,10,False,False,Senior,True,30.0
16,17,2020-01-03 07:00:00,2020-01-01 16:00:00,2020-01-02 02:57:00,Ghaziabad,509,DRUG OFFENSE,61,M,Poison,...,1,January,1,Wednesday,16,False,False,Senior,False,NaN
32,33,2020-01-03 04:00:00,2020-01-02 08:00:00,2020-01-03 03:01:00,Delhi,319,ILLEGAL POSSESSION,73,F,Knife,...,1,January,2,Thursday,8,False,False,Senior,False,NaN
42,43,2020-01-03 03:00:00,2020-01-02 18:00:00,2020-01-03 09:30:00,Delhi,172,FIREARM OFFENSE,40,M,Poison,...,1,January,2,Thursday,18,False,False,Adult,True,74.0

In [4]:
from src.crime_analysis import (
    get_city_crime_counts,
    get_top_crime_types,
    get_monthly_crime_counts,
    get_weekday_crime_counts,
    get_hourly_crime_counts,
    get_city_summary
)

In [5]:
get_city_crime_counts(df)

        City  CrimeCount
0      Delhi        5400
1  Ghaziabad         704
2  Faridabad         354

In [6]:
get_top_crime_types(df, top_n=10)

    CrimeDescription  CrimeCount
0            ROBBERY         339
1  DOMESTIC VIOLENCE         335
2    FIREARM OFFENSE         332
3       DRUG OFFENSE         330
4     IDENTITY THEFT         330
5              FRAUD         326
6         CYBERCRIME         326
7         KIDNAPPING         317
8           HOMICIDE         313
9          VANDALISM         309

In [7]:
get_monthly_crime_counts(df).head(12)

    Year  Month  MonthName  CrimeCount
0   2020      1    January         115
1   2020      2   February         104
2   2020      3      March         135
3   2020      4      April         118
4   2020      5        May         130
5   2020      6       June          97
6   2020      7       July         121
7   2020      8     August         116
8   2020      9  September         114
9   2020     10    October         133
10  2020     11   November         116
11  2020     12   December         122

In [8]:
get_weekday_crime_counts(df)

   DayOfWeek  CrimeCount
0     Monday         902
1    Tuesday         939
2  Wednesday         970
3   Thursday         939
4     Friday         940
5   Saturday         918
6     Sunday         850

In [9]:
get_hourly_crime_counts(df)

    Hour  CrimeCount
0      0         267
1      1         305
2      2         265
3      3         260
4      4         265
5      5         273
6      6         271
7      7         268
8      8         265
9      9         238
10    10         269
11    11         285
12    12         267
13    13         295
14    14         283
15    15         253
16    16         272
17    17         250
18    18         282
19    19         272
20    20         252
21    21         274
22    22         262
23    23         265

In [10]:
get_city_summary(df)

,City,TotalCrimes,UniqueCrimeTypes,AverageVictimAge,AveragePoliceDeployed,ClosedCases,NightCrimes,CaseClosureRate,NightCrimePercentage
0,Delhi,5400,21,44.23,9.95,2646,2267,49.00,41.98
1,Faridabad,354,21,45.87,9.85,187,136,52.82,38.42
2,Ghaziabad,704,21,44.65,10.18,340,285,48.30,40.48

In [11]:
from src.time_pattern_analysis import (
    get_peak_crime_hour,
    get_peak_crime_day,
    get_peak_crime_month,
    get_city_peak_hours,
    get_crime_type_peak_hours,
    get_day_hour_heatmap_data,
    get_time_period_counts
)

In [12]:
get_peak_crime_hour(df)

{'peak_hour': 1, 'crime_count': 305}

In [13]:
get_peak_crime_day(df)

{'peak_day': 'Wednesday', 'crime_count': 970}

In [14]:
get_peak_crime_month(df)

{'peak_month': 'March', 'crime_count': 610}

In [15]:
get_city_peak_hours(df)

        City  Hour  CrimeCount
0      Delhi     1         260
1  Faridabad    16          22
2  Ghaziabad    10          45

In [16]:
get_crime_type_peak_hours(df, top_n=10)

   Crime Description  Hour  CrimeCount
0              FRAUD     1          25
1            ROBBERY    14          24
2         CYBERCRIME    13          23
3  DOMESTIC VIOLENCE    11          22
4           HOMICIDE     3          22
5    FIREARM OFFENSE     1          22
6       DRUG OFFENSE    15          21
7          VANDALISM    18          21
8         KIDNAPPING    14          20
9     IDENTITY THEFT     5          20

In [17]:
get_day_hour_heatmap_data(df)

Hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
DayOfWeek,,,,,,,,,,,,,,,,,,,,,
Monday,48,36,44,41,41,41,36,36,37,29,...,44,37,34,41,41,37,34,35,37,38
Tuesday,44,48,40,39,40,35,35,35,37,38,...,43,38,43,34,46,37,34,47,49,37
Wednesday,23,51,32,40,37,42,38,37,50,33,...,33,32,43,39,47,48,44,31,37,46
Thursday,36,42,36,41,41,40,36,32,37,28,...,37,36,36,40,42,44,40,53,33,42
Friday,34,45,44,21,39,46,43,40,38,39,...,43,38,36,31,34,35,39,38,43,31
Saturday,49,51,34,49,36,29,46,47,30,38,...,42,36,38,32,34,35,32,34,31,38
Sunday,33,32,35,29,31,40,37,41,36,33,...,41,36,42,33,38,36,29,36,32,33

In [18]:
get_time_period_counts(df)

  TimePeriod  CrimeCount
0    Morning        1869
1  Afternoon        1370
2    Evening        1056
3      Night        2163

In [19]:
from src.safety_recommendation import (
    get_city_statistics,
    get_general_safety_tips,
    get_time_based_recommendations,
    get_crime_specific_recommendations,
    generate_safety_recommendation
)

In [20]:
get_city_statistics(df, "Delhi")

{'city': 'Delhi',
 'total_crimes': 5400,
 'peak_hour': 1,
 'peak_time_period': 'Night',
 'peak_day': 'Wednesday',
 'most_common_crime': 'FIREARM OFFENSE',
 'night_crime_percentage': np.float64(41.98),
 'case_closure_rate': np.float64(49.0)}

In [21]:
get_time_based_recommendations(22)

['Avoid travelling alone through isolated areas.',
 'Use verified transport services.',
 'Share live location with a trusted contact.',
 'Keep emergency numbers easily accessible.',
 'Prefer roads with good lighting and public activity.']

In [22]:
get_crime_specific_recommendations("FRAUD")

['Never share OTPs, passwords, or banking PINs.',
 'Verify identities before transferring money.',
 'Avoid opening suspicious links or attachments.']

In [23]:
result = generate_safety_recommendation(
    df=df,
    city="Delhi",
    hour=22,
    crime_type="ASSAULT"
)

result

{'status': 'success',
 'city': 'Delhi',
 'selected_hour': 22,
 'time_period': 'Night',
 'historical_crime_count': 224,
 'average_hourly_count': 225.0,
 'pattern_level': 'Moderate Historical Frequency',
 'city_statistics': {'city': 'Delhi',
  'total_crimes': 5400,
  'peak_hour': 1,
  'peak_time_period': 'Night',
  'peak_day': 'Wednesday',
  'most_common_crime': 'FIREARM OFFENSE',
  'night_crime_percentage': np.float64(41.98),
  'case_closure_rate': np.float64(49.0)},
 'recommendations': ['Avoid travelling alone through isolated areas.',
  'Use verified transport services.',
  'Share live location with a trusted contact.',
  'Keep emergency numbers easily accessible.',
  'Prefer roads with good lighting and public activity.',
  'Avoid confrontations and leave escalating situations.',
  'Stay in well-populated locations.',
  'Contact emergency services when immediate danger exists.',
  'Stay aware of your surroundings, especially in crowded places.',
  'Avoid isolated or poorly lit routes during late hours.']}

In [24]:
from src.heatmap_generator import (
    get_city_map_data,
    create_city_marker_map,
    create_city_heatmap,
    save_map
)

In [25]:
get_city_map_data(df)

        City  CrimeCount  Latitude  Longitude
0      Delhi        5400   28.6139    77.2090
1  Faridabad         354   28.4089    77.3178
2  Ghaziabad         704   28.6692    77.4538

In [26]:
marker_map = create_city_marker_map(df)

marker_map

In [27]:
heatmap = create_city_heatmap(df)

heatmap

In [28]:
marker_output = (
    project_root
    / "reports"
    / "figures"
    / "city_crime_marker_map.html"
)

heatmap_output = (
    project_root
    / "reports"
    / "figures"
    / "city_crime_heatmap.html"
)

save_map(marker_map, marker_output)
save_map(heatmap, heatmap_output)

print("Maps saved successfully.")

Maps saved successfully.

In [29]:
df.columns

Index(['Report Number', 'Date Reported', 'Date of Occurrence',
       'Time of Occurrence', 'City', 'Crime Code', 'Crime Description',
       'Victim Age', 'Victim Gender', 'Weapon Used', 'Crime Domain',
       'Police Deployed', 'Case Closed', 'Date Case Closed', 'Year', 'Month',
       'MonthName', 'Day', 'DayOfWeek', 'Hour', 'IsWeekend', 'IsNightCrime',
       'VictimAgeGroup', 'IsCaseClosed', 'CaseResolutionDays'],
      dtype='str')

In [30]:
df.head()

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,...,Month,MonthName,Day,DayOfWeek,Hour,IsWeekend,IsNightCrime,VictimAgeGroup,IsCaseClosed,CaseResolutionDays
5,6,2020-01-02 03:00:00,2020-01-01 05:00:00,2020-01-01 17:09:00,Delhi,442,ASSAULT,16,M,Firearm,...,1,January,1,Wednesday,5,False,True,Child,True,88.0
10,11,2020-01-02 13:00:00,2020-01-01 10:00:00,2020-01-01 19:42:00,Delhi,260,FRAUD,71,M,Explosives,...,1,January,1,Wednesday,10,False,False,Senior,True,30.0
16,17,2020-01-03 07:00:00,2020-01-01 16:00:00,2020-01-02 02:57:00,Ghaziabad,509,DRUG OFFENSE,61,M,Poison,...,1,January,1,Wednesday,16,False,False,Senior,False,NaN
32,33,2020-01-03 04:00:00,2020-01-02 08:00:00,2020-01-03 03:01:00,Delhi,319,ILLEGAL POSSESSION,73,F,Knife,...,1,January,2,Thursday,8,False,False,Senior,False,NaN
42,43,2020-01-03 03:00:00,2020-01-02 18:00:00,2020-01-03 09:30:00,Delhi,172,FIREARM OFFENSE,40,M,Poison,...,1,January,2,Thursday,18,False,False,Adult,True,74.0

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 6458 entries, 5 to 40159
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Report Number       6458 non-null   int64
 1   Date Reported       6458 non-null   datetime64[us]
 2   Date of Occurrence  6458 non-null   datetime64[us]
 3   Time of Occurrence  6458 non-null   datetime64[us]
 4   City                6458 non-null   str
 5   Crime Code          6458 non-null   int64
 6   Crime Description   6458 non-null   str
 7   Victim Age          6458 non-null   int64
 8   Victim Gender       6458 non-null   str
 9   Weapon Used         6458 non-null   str
 10  Crime Domain        6458 non-null   str
 11  Police Deployed     6458 non-null   int64
 12  Case Closed         6458 non-null   str
 13  Date Case Closed    3173 non-null   datetime64[us]
 14  Year                6458 non-null   int32
 15  Month               6458 non-null   int32
 16  MonthName           6458 non-null   str
 17  Day                 6458 non-null   int32
 18  DayOfWeek           6458 non-null   str
 19  Hour                6458 non-null   int32
 20  IsWeekend           6458 non-null   bool
 21  IsNightCrime        6458 non-null   bool
 22  VictimAgeGroup      6458 non-null   category
 23  IsCaseClosed        6458 non-null   bool
 24  CaseResolutionDays  3173 non-null   float64
dtypes: bool(3), category(1), datetime64[us](4), float64(1), int32(4), int64(4), str(8)
memory usage: 1.3 MB

In [32]:
df["Crime Description"].value_counts()

Crime Description
ROBBERY                339
DOMESTIC VIOLENCE      335
FIREARM OFFENSE        332
DRUG OFFENSE           330
IDENTITY THEFT         330
FRAUD                  326
CYBERCRIME             326
KIDNAPPING             317
HOMICIDE               313
VANDALISM              309
PUBLIC INTOXICATION    304
BURGLARY               302
ILLEGAL POSSESSION     301
SEXUAL ASSAULT         301
COUNTERFEITING         300
EXTORTION              291
VEHICLE - STOLEN       290
SHOPLIFTING            287
ASSAULT                286
ARSON                  281
TRAFFIC VIOLATION      258
Name: count, dtype: int64

In [33]:
print(df["Crime Description"].nunique())

21

# Prepare Data for Machine Learning

In [34]:
# Make a copy of the dataframe
ml_df = df.copy()

# Drop datetime columns (already represented by engineered features)
ml_df = ml_df.drop(columns=[
    "Date Reported",
    "Date of Occurrence",
    "Time of Occurrence",
    "Date Case Closed"
])

# Separate features and target
X = ml_df.drop(columns=["Crime Description"])
y = ml_df["Crime Description"]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

X.head()

Feature Shape: (6458, 20)
Target Shape: (6458,)

,Report Number,City,Crime Code,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Year,Month,MonthName,Day,DayOfWeek,Hour,IsWeekend,IsNightCrime,VictimAgeGroup,IsCaseClosed,CaseResolutionDays
5,6,Delhi,442,16,M,Firearm,Violent Crime,18,Yes,2020,1,January,1,Wednesday,5,False,True,Child,True,88.0
10,11,Delhi,260,71,M,Explosives,Other Crime,5,Yes,2020,1,January,1,Wednesday,10,False,False,Senior,True,30.0
16,17,Ghaziabad,509,61,M,Poison,Other Crime,6,No,2020,1,January,1,Wednesday,16,False,False,Senior,False,NaN
32,33,Delhi,319,73,F,Knife,Other Crime,19,No,2020,1,January,2,Thursday,8,False,False,Senior,False,NaN
42,43,Delhi,172,40,M,Poison,Fire Accident,10,Yes,2020,1,January,2,Thursday,18,False,False,Adult,True,74.0

In [35]:
print("Categorical Columns:")
print(X.select_dtypes(include=["object", "category"]).columns.tolist())

print("\nNumerical Columns:")
print(X.select_dtypes(include=["int64", "int32", "float64"]).columns.tolist())

print("\nBoolean Columns:")
print(X.select_dtypes(include=["bool"]).columns.tolist())

Categorical Columns:
['City', 'Victim Gender', 'Weapon Used', 'Crime Domain', 'Case Closed', 'MonthName', 'DayOfWeek', 'VictimAgeGroup']

Numerical Columns:
['Report Number', 'Crime Code', 'Victim Age', 'Police Deployed', 'Year', 'Month', 'Day', 'Hour', 'CaseResolutionDays']

Boolean Columns:
['IsWeekend', 'IsNightCrime', 'IsCaseClosed']

C:\Users\Admin\AppData\Local\Temp\ipykernel_1380\4112121496.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(X.select_dtypes(include=["object", "category"]).columns.tolist())

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

# Remove ID column
X = X.drop(columns=["Report Number", "CaseResolutionDays"])

# Update feature lists
categorical_features = [
    "City",
    "Victim Gender",
    "Weapon Used",
    "Crime Domain",
    "Case Closed",
    "MonthName",
    "DayOfWeek",
    "VictimAgeGroup"
]

numerical_features = [
    "Crime Code",
    "Victim Age",
    "Police Deployed",
    "Year",
    "Month",
    "Day",
    "Hour"
]

boolean_features = [
    "IsWeekend",
    "IsNightCrime",
    "IsCaseClosed"
]

# Numerical pipeline
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

# Categorical pipeline
categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine preprocessing
preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numerical_features),
    ("cat", categorical_transformer, categorical_features),
    ("bool", "passthrough", boolean_features)
])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Set:", X_train.shape)
print("Testing Set :", X_test.shape)

Training Set: (5166, 18)
Testing Set : (1292, 18)

In [37]:
print(X.columns)

Index(['City', 'Crime Code', 'Victim Age', 'Victim Gender', 'Weapon Used',
       'Crime Domain', 'Police Deployed', 'Case Closed', 'Year', 'Month',
       'MonthName', 'Day', 'DayOfWeek', 'Hour', 'IsWeekend', 'IsNightCrime',
       'VictimAgeGroup', 'IsCaseClosed'],
      dtype='str')

# Random Forest Classifier

In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Build the complete pipeline
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

# Train the model
rf_pipeline.fit(X_train, y_train)

# Predictions
y_pred = rf_pipeline.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix Shape:")
print(confusion_matrix(y_test, y_pred).shape)

Accuracy: 0.1858

Classification Report:

                     precision    recall  f1-score   support

              ARSON       0.35      0.23      0.28        56
            ASSAULT       0.19      0.18      0.18        57
           BURGLARY       0.05      0.05      0.05        60
     COUNTERFEITING       0.18      0.18      0.18        60
         CYBERCRIME       0.10      0.11      0.10        65
  DOMESTIC VIOLENCE       0.15      0.19      0.17        67
       DRUG OFFENSE       0.12      0.15      0.14        66
          EXTORTION       0.07      0.07      0.07        58
    FIREARM OFFENSE       0.50      0.64      0.56        67
              FRAUD       0.10      0.12      0.11        65
           HOMICIDE       0.03      0.03      0.03        63
     IDENTITY THEFT       0.20      0.21      0.20        66
 ILLEGAL POSSESSION       0.10      0.08      0.09        60
         KIDNAPPING       0.08      0.08      0.08        64
PUBLIC INTOXICATION       0.08      0.08      0.08        61
            ROBBERY       0.15      0.16      0.16        68
     SEXUAL ASSAULT       0.16      0.15      0.16        60
        SHOPLIFTING       0.12      0.11      0.11        57
  TRAFFIC VIOLATION       1.00      1.00      1.00        52
          VANDALISM       0.10      0.08      0.09        62
   VEHICLE - STOLEN       0.11      0.07      0.08        58

           accuracy                           0.19      1292
          macro avg       0.19      0.19      0.19      1292
       weighted avg       0.18      0.19      0.18      1292


Confusion Matrix Shape:
(21, 21)

# Decision Tree Classifier

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Decision Tree Pipeline
dt_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", DecisionTreeClassifier(
        random_state=42
    ))
])

# Train
dt_pipeline.fit(X_train, y_train)

# Predict
y_pred_dt = dt_pipeline.predict(X_test)

# Accuracy
dt_accuracy = accuracy_score(y_test, y_pred_dt)

print(f"Decision Tree Accuracy: {dt_accuracy:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dt))

print("\nConfusion Matrix Shape:")
print(confusion_matrix(y_test, y_pred_dt).shape)

Decision Tree Accuracy: 0.1865

Classification Report:

                     precision    recall  f1-score   support

              ARSON       0.43      0.46      0.45        56
            ASSAULT       0.13      0.14      0.14        57
           BURGLARY       0.08      0.08      0.08        60
     COUNTERFEITING       0.09      0.08      0.09        60
         CYBERCRIME       0.05      0.05      0.05        65
  DOMESTIC VIOLENCE       0.20      0.22      0.21        67
       DRUG OFFENSE       0.12      0.14      0.12        66
          EXTORTION       0.07      0.09      0.08        58
    FIREARM OFFENSE       0.52      0.49      0.51        67
              FRAUD       0.11      0.09      0.10        65
           HOMICIDE       0.06      0.05      0.05        63
     IDENTITY THEFT       0.15      0.12      0.13        66
 ILLEGAL POSSESSION       0.12      0.10      0.11        60
         KIDNAPPING       0.09      0.11      0.10        64
PUBLIC INTOXICATION       0.07      0.08      0.08        61
            ROBBERY       0.26      0.29      0.27        68
     SEXUAL ASSAULT       0.17      0.18      0.18        60
        SHOPLIFTING       0.05      0.05      0.05        57
  TRAFFIC VIOLATION       1.00      1.00      1.00        52
          VANDALISM       0.08      0.06      0.07        62
   VEHICLE - STOLEN       0.16      0.12      0.14        58

           accuracy                           0.19      1292
          macro avg       0.19      0.19      0.19      1292
       weighted avg       0.19      0.19      0.19      1292


Confusion Matrix Shape:
(21, 21)

# Logistic Regression

In [40]:
from sklearn.linear_model import LogisticRegression

lr_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        max_iter=2000,
        random_state=42
    ))
])

# Train
lr_pipeline.fit(X_train, y_train)

# Predict
y_pred_lr = lr_pipeline.predict(X_test)

# Accuracy
lr_accuracy = accuracy_score(y_test, y_pred_lr)

print(f"Logistic Regression Accuracy: {lr_accuracy:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.1803

Classification Report:

                     precision    recall  f1-score   support

              ARSON       0.38      0.18      0.24        56
            ASSAULT       0.17      0.11      0.13        57
           BURGLARY       0.05      0.08      0.06        60
     COUNTERFEITING       0.00      0.00      0.00        60
         CYBERCRIME       0.07      0.05      0.06        65
  DOMESTIC VIOLENCE       0.11      0.13      0.12        67
       DRUG OFFENSE       0.08      0.15      0.11        66
          EXTORTION       0.06      0.07      0.07        58
    FIREARM OFFENSE       0.53      0.76      0.62        67
              FRAUD       0.12      0.22      0.15        65
           HOMICIDE       0.04      0.05      0.04        63
     IDENTITY THEFT       0.14      0.15      0.14        66
 ILLEGAL POSSESSION       0.06      0.03      0.04        60
         KIDNAPPING       0.17      0.11      0.13        64
PUBLIC INTOXICATION       0.13      0.08      0.10        61
            ROBBERY       0.22      0.24      0.23        68
     SEXUAL ASSAULT       0.23      0.25      0.24        60
        SHOPLIFTING       0.09      0.04      0.05        57
  TRAFFIC VIOLATION       1.00      1.00      1.00        52
          VANDALISM       0.09      0.10      0.09        62
   VEHICLE - STOLEN       0.06      0.05      0.06        58

           accuracy                           0.18      1292
          macro avg       0.18      0.18      0.18      1292
       weighted avg       0.18      0.18      0.17      1292

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# Gradient Boosting

In [41]:
from sklearn.ensemble import GradientBoostingClassifier

gb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", GradientBoostingClassifier(
        random_state=42
    ))
])

# Train
gb_pipeline.fit(X_train, y_train)

# Predict
y_pred_gb = gb_pipeline.predict(X_test)

# Accuracy
gb_accuracy = accuracy_score(y_test, y_pred_gb)

print(f"Gradient Boosting Accuracy: {gb_accuracy:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_gb))

Gradient Boosting Accuracy: 0.1811

Classification Report:

                     precision    recall  f1-score   support

              ARSON       0.43      0.38      0.40        56
            ASSAULT       0.15      0.16      0.15        57
           BURGLARY       0.11      0.08      0.09        60
     COUNTERFEITING       0.08      0.08      0.08        60
         CYBERCRIME       0.04      0.05      0.05        65
  DOMESTIC VIOLENCE       0.18      0.21      0.19        67
       DRUG OFFENSE       0.09      0.11      0.10        66
          EXTORTION       0.08      0.09      0.08        58
    FIREARM OFFENSE       0.53      0.58      0.55        67
              FRAUD       0.14      0.18      0.16        65
           HOMICIDE       0.06      0.06      0.06        63
     IDENTITY THEFT       0.18      0.20      0.19        66
 ILLEGAL POSSESSION       0.06      0.05      0.06        60
         KIDNAPPING       0.04      0.03      0.04        64
PUBLIC INTOXICATION       0.10      0.08      0.09        61
            ROBBERY       0.10      0.12      0.11        68
     SEXUAL ASSAULT       0.11      0.08      0.09        60
        SHOPLIFTING       0.16      0.18      0.17        57
  TRAFFIC VIOLATION       1.00      1.00      1.00        52
          VANDALISM       0.12      0.11      0.12        62
   VEHICLE - STOLEN       0.12      0.09      0.10        58

           accuracy                           0.18      1292
          macro avg       0.18      0.19      0.18      1292
       weighted avg       0.18      0.18      0.18      1292

# Model Summary

In [42]:
import pandas as pd

comparison = pd.DataFrame({
    "Model": [
        "Random Forest",
        "Decision Tree",
        "Logistic Regression",
        "Gradient Boosting"
    ],
    "Accuracy": [
        accuracy,
        dt_accuracy,
        lr_accuracy,
        gb_accuracy
    ]
})

comparison = comparison.sort_values(
    by="Accuracy",
    ascending=False
).reset_index(drop=True)

comparison

                 Model  Accuracy
0        Decision Tree  0.186533
1        Random Forest  0.185759
2    Gradient Boosting  0.181115
3  Logistic Regression  0.180341

# Hyperparameter Tuning - Random Forest

In [43]:
from sklearn.model_selection import GridSearchCV

# Random Forest Pipeline
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))
])

# Parameters to test
param_grid = {
    "classifier__n_estimators": [100, 200, 300],
    "classifier__max_depth": [10, 20, None],
    "classifier__min_samples_split": [2, 5],
    "classifier__min_samples_leaf": [1, 2]
}

# Grid Search
grid_search = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

# Train
grid_search.fit(X_train, y_train)

# Best model
best_model = grid_search.best_estimator_

print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest Cross Validation Accuracy:")
print(grid_search.best_score_)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Parameters:
{'classifier__max_depth': 10, 'classifier__min_samples_leaf': 2, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 300}

Best Cross Validation Accuracy:
0.1939615512085698

In [44]:
from sklearn.metrics import accuracy_score, classification_report

# Prediction
y_pred_best = best_model.predict(X_test)

# Accuracy
best_accuracy = accuracy_score(y_test, y_pred_best)

print(f"Tuned Random Forest Accuracy: {best_accuracy:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_best))

Tuned Random Forest Accuracy: 0.1703

Classification Report:

                     precision    recall  f1-score   support

              ARSON       0.33      0.16      0.22        56
            ASSAULT       0.18      0.12      0.15        57
           BURGLARY       0.00      0.00      0.00        60
     COUNTERFEITING       0.12      0.07      0.09        60
         CYBERCRIME       0.06      0.09      0.07        65
  DOMESTIC VIOLENCE       0.12      0.18      0.15        67
       DRUG OFFENSE       0.07      0.14      0.09        66
          EXTORTION       0.06      0.05      0.05        58
    FIREARM OFFENSE       0.51      0.73      0.60        67
              FRAUD       0.08      0.14      0.10        65
           HOMICIDE       0.05      0.05      0.05        63
     IDENTITY THEFT       0.18      0.18      0.18        66
 ILLEGAL POSSESSION       0.11      0.07      0.08        60
         KIDNAPPING       0.09      0.09      0.09        64
PUBLIC INTOXICATION       0.09      0.05      0.06        61
            ROBBERY       0.15      0.22      0.18        68
     SEXUAL ASSAULT       0.13      0.12      0.12        60
        SHOPLIFTING       0.08      0.04      0.05        57
  TRAFFIC VIOLATION       1.00      1.00      1.00        52
          VANDALISM       0.10      0.10      0.10        62
   VEHICLE - STOLEN       0.11      0.03      0.05        58

           accuracy                           0.17      1292
          macro avg       0.17      0.17      0.17      1292
       weighted avg       0.17      0.17      0.16      1292

In [45]:
print(grid_search.best_params_)

{'classifier__max_depth': 10, 'classifier__min_samples_leaf': 2, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 300}

In [46]:
print(grid_search.best_score_)

0.1939615512085698

In [47]:
print(best_accuracy)

0.17027863777089783

In [48]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

final_rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

final_rf_pipeline.fit(X_train, y_train)

print("Final Random Forest trained successfully")

Final Random Forest trained successfully

In [49]:
rf_model = final_rf_pipeline.named_steps["classifier"]

feature_names = (
    final_rf_pipeline
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

importance = rf_model.feature_importances_

print("Number of features:", len(feature_names))
print("Number of importance values:", len(importance))

Number of features: 53
Number of importance values: 53

In [50]:
import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

feature_importance.head(20)

                               Feature  Importance
0                      num__Crime Code    0.078250
1                      num__Victim Age    0.069819
2                             num__Day    0.068601
3                            num__Hour    0.065473
4                 num__Police Deployed    0.063962
5                           num__Month    0.044021
6                            num__Year    0.041790
7      cat__Crime Domain_Violent Crime    0.039193
8      cat__Crime Domain_Fire Accident    0.038685
9        cat__Crime Domain_Other Crime    0.036348
10  cat__Crime Domain_Traffic Fatality    0.028564
11                  bool__IsNightCrime    0.016959
12                cat__Victim Gender_F    0.015254
13                cat__Victim Gender_M    0.014569
14             cat__Weapon Used_Poison    0.012377
15                     bool__IsWeekend    0.012325
16            cat__Weapon Used_Unknown    0.012142
17              cat__Weapon Used_Knife    0.012128
18       cat__Weapon Used_Blunt Object    0.012056
19                  bool__IsCaseClosed    0.011966

In [51]:
df.groupby("Crime Code")["Crime Description"].nunique().sort_values(ascending=False).head(10)

Crime Code
360    16
233    16
457    16
557    15
381    15
147    15
219    15
509    14
125    14
551    14
Name: Crime Description, dtype: int64

# Retraining the RFC model

In [52]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

final_rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

final_rf_pipeline.fit(X_train, y_train)

y_pred_final = final_rf_pipeline.predict(X_test)

final_accuracy = accuracy_score(y_test, y_pred_final)

print(f"Final Random Forest Accuracy: {final_accuracy:.4f}")

Final Random Forest Accuracy: 0.1858

In [53]:
df.groupby("Crime Description")["Crime Domain"].nunique().sort_values(
    ascending=False
).head(21)

Crime Description
ARSON                  1
ASSAULT                1
BURGLARY               1
COUNTERFEITING         1
CYBERCRIME             1
DOMESTIC VIOLENCE      1
DRUG OFFENSE           1
EXTORTION              1
FIREARM OFFENSE        1
FRAUD                  1
HOMICIDE               1
IDENTITY THEFT         1
ILLEGAL POSSESSION     1
KIDNAPPING             1
PUBLIC INTOXICATION    1
ROBBERY                1
SEXUAL ASSAULT         1
SHOPLIFTING            1
TRAFFIC VIOLATION      1
VANDALISM              1
VEHICLE - STOLEN       1
Name: Crime Domain, dtype: int64

In [54]:
df["Crime Description"].value_counts()

Crime Description
ROBBERY                339
DOMESTIC VIOLENCE      335
FIREARM OFFENSE        332
DRUG OFFENSE           330
IDENTITY THEFT         330
FRAUD                  326
CYBERCRIME             326
KIDNAPPING             317
HOMICIDE               313
VANDALISM              309
PUBLIC INTOXICATION    304
BURGLARY               302
ILLEGAL POSSESSION     301
SEXUAL ASSAULT         301
COUNTERFEITING         300
EXTORTION              291
VEHICLE - STOLEN       290
SHOPLIFTING            287
ASSAULT                286
ARSON                  281
TRAFFIC VIOLATION      258
Name: count, dtype: int64

In [55]:
risk_mapping = {
    "HOMICIDE": "High",
    "KIDNAPPING": "High",
    "SEXUAL ASSAULT": "High",
    "FIREARM OFFENSE": "High",
    "DOMESTIC VIOLENCE": "High",
    "ASSAULT": "High",
    "ARSON": "High",

    "ROBBERY": "Medium",
    "BURGLARY": "Medium",
    "VEHICLE - STOLEN": "Medium",
    "DRUG OFFENSE": "Medium",
    "EXTORTION": "Medium",
    "ILLEGAL POSSESSION": "Medium",
    "VANDALISM": "Medium",

    "FRAUD": "Low",
    "CYBERCRIME": "Low",
    "IDENTITY THEFT": "Low",
    "COUNTERFEITING": "Low",
    "SHOPLIFTING": "Low",
    "PUBLIC INTOXICATION": "Low",
    "TRAFFIC VIOLATION": "Low"
}

df["RiskLevel"] = df["Crime Description"].map(risk_mapping)

print(df["RiskLevel"].value_counts())

RiskLevel
High      2165
Medium    2162
Low       2131
Name: count, dtype: int64

# Risk Level Prediction Model

In [58]:
# Create ML dataset for Risk Level Prediction

risk_df = df.copy()

# Remove columns not available or causing target leakage
risk_df = risk_df.drop(columns=[
    "Crime Description",
    "Crime Domain",
    "CaseResolutionDays"
])

# Features and Target
X = risk_df.drop(columns=[
    "RiskLevel",
    "Report Number"
])

y = risk_df["RiskLevel"]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nTarget Distribution:")
print(y.value_counts())

Feature Shape: (6458, 21)
Target Shape: (6458,)

Target Distribution:
RiskLevel
High      2165
Medium    2162
Low       2131
Name: count, dtype: int64

In [59]:
print("Categorical Columns:")
print(X.select_dtypes(include=["object", "category", "string"]).columns.tolist())

print("\nNumerical Columns:")
print(X.select_dtypes(include=["int64", "int32", "float64"]).columns.tolist())

print("\nBoolean Columns:")
print(X.select_dtypes(include=["bool"]).columns.tolist())

Categorical Columns:
['City', 'Victim Gender', 'Weapon Used', 'Case Closed', 'MonthName', 'DayOfWeek', 'VictimAgeGroup']

Numerical Columns:
['Crime Code', 'Victim Age', 'Police Deployed', 'Year', 'Month', 'Day', 'Hour']

Boolean Columns:
['IsWeekend', 'IsNightCrime', 'IsCaseClosed']

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

categorical_features = [
    "City",
    "Victim Gender",
    "Weapon Used",
    "Case Closed",
    "MonthName",
    "DayOfWeek",
    "VictimAgeGroup"
]

numerical_features = [
    "Crime Code",
    "Victim Age",
    "Police Deployed",
    "Year",
    "Month",
    "Day",
    "Hour"
]

boolean_features = [
    "IsWeekend",
    "IsNightCrime",
    "IsCaseClosed"
]

numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

risk_preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numerical_features),
    ("cat", categorical_transformer, categorical_features),
    ("bool", "passthrough", boolean_features)
])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Set:", X_train.shape)
print("Testing Set:", X_test.shape)

Training Set: (5166, 21)
Testing Set: (1292, 21)

In [61]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

risk_rf_pipeline = Pipeline([
    ("preprocessor", risk_preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

risk_rf_pipeline.fit(X_train, y_train)

y_pred_risk = risk_rf_pipeline.predict(X_test)

risk_accuracy = accuracy_score(y_test, y_pred_risk)

print(f"Risk-Level Random Forest Accuracy: {risk_accuracy:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_risk))

Risk-Level Random Forest Accuracy: 0.3460

Classification Report:

              precision    recall  f1-score   support

        High       0.36      0.36      0.36       433
         Low       0.33      0.34      0.34       426
      Medium       0.34      0.34      0.34       433

    accuracy                           0.35      1292
   macro avg       0.35      0.35      0.35      1292
weighted avg       0.35      0.35      0.35      1292